param(
	[string]$GameRoot = "C:\Program Files (x86)\Steam\steamapps\common\Hearts of Iron IV"
)

$ErrorActionPreference = "Stop"

$projectRoot = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
$sourcePath = Join-Path $GameRoot 'interface\countrytechtreeview.gui'
$targetPath = Join-Path $projectRoot 'Mod\interface\countrytechtreeview.gui'
$expectedSourceHash = 'FEC641FB738AB59369CAC40AE902FDBA793BED7CBAA2C807756207A2E1F01045'

if (-not (Test-Path -LiteralPath $sourcePath -PathType Leaf)) {
	throw "HOI4 technology-tree interface was not found: $sourcePath"
}

$actualSourceHash = (Get-FileHash -LiteralPath $sourcePath -Algorithm SHA256).Hash
if ($actualSourceHash -cne $expectedSourceHash) {
	throw "Unsupported countrytechtreeview.gui hash $actualSourceHash. This builder is pinned to HOI4 1.19.2.0 ($expectedSourceHash)."
}

$text = [IO.File]::ReadAllText($sourcePath)
if ($text.Contains("`r`n")) {
	throw 'Expected the HOI4 1.19.2 technology-tree interface to use LF line endings.'
}

function Add-BeforeUniqueAnchor {
	param(
		[Parameter(Mandatory)] [string]$InputText,
		[Parameter(Mandatory)] [string]$Anchor,
		[Parameter(Mandatory)] [string]$Insertion,
		[Parameter(Mandatory)] [string]$Description
	)

	$count = [regex]::Matches($InputText, [regex]::Escape($Anchor)).Count
	if ($count -ne 1) {
		throw "Expected one $Description anchor, found $count."
	}

	$InputText.Replace($Anchor, $Insertion + "`n`n" + $Anchor)
}

$folderBlock = @'
		# COI_ALIEN_TECH_FOLDER_BEGIN - generated by Build-AlienTechnologyUI.ps1
		containerWindowType = {
			name = "coi_alien_technology_folder"
			position = { x = 0 y = 47 }
			size = { width = 100%% height = 100%% }
			margin = { top = 13 left = 13 bottom = 24 right = 25 }
			drag_scroll = { left middle }
			verticalScrollbar = "right_vertical_slider"
			horizontalScrollbar = "bottom_horizontal_slider"
			scroll_wheel_factor = 40

			background = {
				name = "Background"
				quadTextureSprite = "GFX_tiled_window_2b_border"
			}

			containerWindowType = {
				name = "techtree_stripes"
				position = { x = 0 y = 0 }
				size = {
					width = 1700 height = 1150
					min = { width = 100%% height = 100%% }
				}
				clipping = no
				background = {
					name = "Background"
					quadTextureSprite = "GFX_techtree_stripes"
				}
			}

			instantTextBoxType = {
				name = "coi_alien_materials_title"
				position = { x = 25 y = 75 }
				font = "hoi_22tech"
				text = "coi_alien_technology_materials_title"
				maxWidth = 240
				maxHeight = 40
				format = center
			}

			instantTextBoxType = {
				name = "coi_alien_propulsion_title"
				position = { x = 300 y = 75 }
				font = "hoi_22tech"
				text = "coi_alien_technology_propulsion_title"
				maxWidth = 240
				maxHeight = 40
				format = center
			}

			instantTextBoxType = {
				name = "coi_alien_energy_title"
				position = { x = 575 y = 75 }
				font = "hoi_22tech"
				text = "coi_alien_technology_energy_title"
				maxWidth = 240
				maxHeight = 40
				format = center
			}

			instantTextBoxType = {
				name = "coi_alien_computation_title"
				position = { x = 850 y = 75 }
				font = "hoi_22tech"
				text = "coi_alien_technology_computation_title"
				maxWidth = 240
				maxHeight = 40
				format = center
			}

			instantTextBoxType = {
				name = "coi_alien_human_sciences_title"
				position = { x = 1125 y = 75 }
				font = "hoi_22tech"
				text = "coi_alien_technology_human_sciences_title"
				maxWidth = 240
				maxHeight = 40
				format = center
			}

			instantTextBoxType = {
				name = "coi_alien_fabrication_title"
				position = { x = 1400 y = 75 }
				font = "hoi_22tech"
				text = "coi_alien_technology_fabrication_title"
				maxWidth = 240
				maxHeight = 40
				format = center
			}

			# Each disconnected technology graph requires a root-ID grid box.
			gridboxtype = {
				name = "coi_alien_adaptive_metamaterials_tree"
				position = { x = 25 y = 135 }
				size = { width = 240 height = 1000 }
				slotsize = { width = 70 height = 90 }
				format = "UP"
			}

			gridboxtype = {
				name = "coi_alien_inertial_field_theory_tree"
				position = { x = 300 y = 135 }
				size = { width = 240 height = 1000 }
				slotsize = { width = 70 height = 90 }
				format = "UP"
			}

			gridboxtype = {
				name = "coi_alien_coherent_energy_control_tree"
				position = { x = 575 y = 135 }
				size = { width = 240 height = 1000 }
				slotsize = { width = 70 height = 90 }
				format = "UP"
			}

			gridboxtype = {
				name = "coi_alien_predictive_computation_tree"
				position = { x = 850 y = 135 }
				size = { width = 240 height = 1000 }
				slotsize = { width = 70 height = 90 }
				format = "UP"
			}

			gridboxtype = {
				name = "coi_alien_comparative_human_ethology_tree"
				position = { x = 1125 y = 135 }
				size = { width = 240 height = 1000 }
				slotsize = { width = 70 height = 90 }
				format = "UP"
			}

			gridboxtype = {
				name = "coi_alien_expeditionary_pattern_libraries_tree"
				position = { x = 1400 y = 135 }
				size = { width = 240 height = 1000 }
				slotsize = { width = 70 height = 90 }
				format = "UP"
			}
		}
		# COI_ALIEN_TECH_FOLDER_END
'@

$folderAnchor = "`t`tcontainerWindowType = {`n`t`t`tname = `"folder_tabs`""
$text = Add-BeforeUniqueAnchor -InputText $text -Anchor $folderAnchor -Insertion $folderBlock -Description 'folder-tabs'

$tabBlock = @'
			# COI_ALIEN_TECH_TAB_BEGIN - generated by Build-AlienTechnologyUI.ps1
			buttonType = {
				name = "coi_alien_technology_folder_tab"
				position = { x = 22 y = 0 }
				quadTextureSprite = "GFX_techtree_engineering_tab"
				frame = 1
				clicksound = ui_research_tab_engineering
			}
			# COI_ALIEN_TECH_TAB_END
'@

$tabAnchor = "`t`t`ticonType = {`n`t`t`t`tname = `"highlight_industry_folder`""
$text = Add-BeforeUniqueAnchor -InputText $text -Anchor $tabAnchor -Insertion $tabBlock -Description 'industry-highlight'

if ([regex]::Matches($text, 'name\s*=\s*"coi_alien_technology_folder"').Count -ne 1) {
	throw 'Generated technology UI does not contain exactly one alien folder container.'
}
if ([regex]::Matches($text, 'name\s*=\s*"coi_alien_technology_folder_tab"').Count -ne 1) {
	throw 'Generated technology UI does not contain exactly one alien folder tab.'
}

$targetDirectory = Split-Path -Parent $targetPath
New-Item -ItemType Directory -Path $targetDirectory -Force | Out-Null
[IO.File]::WriteAllText($targetPath, $text, [Text.UTF8Encoding]::new($false))

Write-Host "Built $targetPath from the pinned HOI4 1.19.2.0 research interface."
