param(
	[string]$GameRoot = "C:\Program Files (x86)\Steam\steamapps\common\Hearts of Iron IV"
)

$ErrorActionPreference = "Stop"

$projectRoot = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
$sourcePath = Join-Path $GameRoot 'interface\countryintelligenceagencyview.gui'
$targetPath = Join-Path $projectRoot 'Mod\interface\countryintelligenceagencyview.gui'
$expectedSourceHash = '00153F0968113C3F29D914BDA227C729BA5D95F5888135C0DD98DB89748EF3E5'

if (-not (Test-Path -LiteralPath $sourcePath -PathType Leaf)) {
	throw "HOI4 intelligence-agency interface was not found: $sourcePath"
}

$actualSourceHash = (Get-FileHash -LiteralPath $sourcePath -Algorithm SHA256).Hash
if ($actualSourceHash -cne $expectedSourceHash) {
	throw "Unsupported countryintelligenceagencyview.gui hash $actualSourceHash. This builder is pinned to HOI4 1.19.2.0 ($expectedSourceHash)."
}

$text = [IO.File]::ReadAllText($sourcePath)
if ($text.Contains("`r`n")) {
	throw 'Expected the HOI4 1.19.2 intelligence-agency interface to use LF line endings.'
}

$anchor = "`t`t`ticonType = { name = `"token_resistance_contacts_icon`" }"
$anchorCount = [regex]::Matches($text, [regex]::Escape($anchor)).Count
if ($anchorCount -ne 1) {
	throw "Expected one resistance-token UI anchor, found $anchorCount."
}

$insertion = @'
			# COI_ALIEN_OPERATION_TOKENS_BEGIN - generated by Build-AlienIntelligenceUI.ps1
			iconType = { name = "coi_alien_token_surface_profile_icon" }
			iconType = { name = "coi_alien_token_institutional_access_icon" }
			iconType = { name = "coi_alien_token_research_access_icon" }
			# COI_ALIEN_OPERATION_TOKENS_END
'@

$text = $text.Replace($anchor, $anchor + "`n" + $insertion)

foreach ($tokenId in @(
	'coi_alien_token_surface_profile',
	'coi_alien_token_institutional_access',
	'coi_alien_token_research_access'
)) {
	$pattern = 'name\s*=\s*"' + [regex]::Escape($tokenId) + '_icon"'
	if ([regex]::Matches($text, $pattern).Count -ne 1) {
		throw "Generated intelligence UI does not contain exactly one $tokenId icon hook."
	}
}

$targetDirectory = Split-Path -Parent $targetPath
New-Item -ItemType Directory -Path $targetDirectory -Force | Out-Null
[IO.File]::WriteAllText($targetPath, $text, [Text.UTF8Encoding]::new($false))

Write-Host "Built $targetPath from the pinned HOI4 1.19.2.0 intelligence interface."
